Repository canonical/jenkins-k8s-operator, pull requests merged in 2023-12, with the labels that each got.

#75 fix: prevent hooks before preconditions ready
  src-docs/actions.py.md
  src-docs/agent.py.md
  src-docs/charm.py.md
  src-docs/state.py.md
  src/actions.py
  src/agent.py
  src/charm.py
  src/jenkins.py
  src/state.py
  tests/unit/conftest.py
  tests/unit/helpers.py
  tests/unit/test_actions.py
  tests/unit/test_charm.py
  tests/unit/test_jenkins.py
  tests/unit/test_state.py
Labels: trivial, Libraries: OK

#77 Fix/agent relation
  src/agent.py
Labels: bug, Libraries: OK, urgent

#78 chore: comment on deferred events.
  src/agent.py
  src/charm.py
Labels: trivial, Libraries: OK

#81 chore: bump jenkins-k8s LTS version
  jenkins_rock/rockcraft.yaml
Labels: Libraries: OK

#80 feat: open port
  src/charm.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tox.ini
Labels: trivial, Libraries: OK

#83 Use self-hosted runner for integration test
  .github/workflows/integration_test.yaml
  tox.ini
Labels: trivial, Libraries: OK

#85 fix: integration test & workflow
  .github/workflows/integration_test.yaml
  tests/integration/helpers.py
  tests/integration/test_jenkins.py
  tests/integration/test_plugins.py
Labels: trivial, Libraries: Out of sync

#84 chore: remove patched CVEs
  .trivyignore
Labels: trivial, Libraries: Out of sync

#82 fix: plugin remove
  src-docs/jenkins.py.md
  src/charm.py
  src/jenkins.py
  tests/integration/constants.py
  tests/integration/test_plugins.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_jenkins.py
Labels: trivial, Libraries: Out of sync

#86 fix: agent connection through direct tunnel
  src-docs/jenkins.py.md
  src/agent.py
  src/jenkins.py
  tests/unit/conftest.py
  tests/unit/test_agent.py
  tests/unit/test_jenkins.py
Labels: trivial, Libraries: Out of sync
