Repository canonical/jenkins-k8s-operator, pull requests merged in 2023-11, with the labels that each got.

#46 fix: filter unit running job
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_plugins.py
Labels: trivial, Libraries: OK

#45 chore: update jenkins lts version
  jenkins_rock/rockcraft.yaml
  src/jenkins.py
  tests/integration/helpers.py
  tests/integration/test_k8s_agent.py
  tests/unit/conftest.py
Labels: trivial, Libraries: OK

#47 test: blueocean plugin
  tests/integration/test_plugins.py
Labels: trivial, Libraries: OK

#48 test: ssh_agent plugin
  tests/integration/helpers.py
  tests/integration/test_plugins.py
Labels: trivial, Libraries: OK

#49 test: thinbackup plugin
  tests/integration/test_plugins.py
Labels: trivial, Libraries: OK

#53 test: rebuild plugin
  tests/integration/test_plugins.py
Labels: trivial, Libraries: OK

#57 fix: use api token instaed of password
  src-docs/jenkins.py.md
  src/charm.py
  src/jenkins.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_jenkins.py
Labels: trivial, complex, Libraries: OK

#58 Ingress v2 support
  lib/charms/traefik_k8s/v1/ingress.py
  metadata.yaml
  src-docs/charm.py.md
  src-docs/ingress.py.md
  src/charm.py
  src/ingress.py
  tests/integration/conftest.py
  tests/integration/test_ingress.py
Labels: trivial, Libraries: OK

#59 chore: ignore unpatched vuln
  .trivyignore
Labels: trivial, Libraries: OK

#61 chore: rename fixtures for clarity
  tests/integration/conftest.py
  tests/integration/test_k8s_agent.py
  tests/integration/test_machine_agent.py
  tests/integration/test_plugins.py
Labels: trivial, Libraries: OK

#60 chore: remove jenkins auto-update
  config.yaml
  src-docs/charm.py.md
  src-docs/jenkins.py.md
  src/charm.py
  src/jenkins.py
  src/status.py
  tests/integration/conftest.py
  tests/integration/test_jenkins.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_jenkins.py
  tests/unit/test_status.py
  tests/unit/types_.py
Labels: complex, Libraries: OK

#52 test: bzr job config UI test
  tests/integration/files/bzr_plugin_job_xml.j2
  tests/integration/test_plugins.py
Labels: trivial, Libraries: OK

#56 mount storage for jenkins_home
  metadata.yaml
  tests/integration/test_jenkins.py
Labels: complex, Libraries: OK

#55 test: oic-auth plugin test
  .woke.yaml
  src-docs/jenkins.py.md
  src/charm.py
  src/jenkins.py
  tests/integration/conftest.py
  tests/integration/requirements.txt
  tests/integration/test_plugins.py
  tests/integration/types_.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_jenkins.py
  tox.ini
Labels: trivial, Libraries: OK

#62 test: refactor raise exceptions lambda
  tests/integration/test_jenkins.py
  tests/integration/test_plugins.py
  tests/unit/conftest.py
  tests/unit/test_actions.py
  tests/unit/test_agent.py
  tests/unit/test_charm.py
  tests/unit/test_jenkins.py
Labels: trivial, Libraries: OK

#65 test: fix rebuilder test
  tests/integration/test_plugins.py
Labels: trivial, Libraries: OK

#63 ISD-1307 Update permission when mounting storage
  src/charm.py
  tests/integration/test_jenkins.py
  tests/unit/test_charm.py
Labels: bug, Libraries: OK

#70 fix: juju 3.1 compatible cos stack
  .github/workflows/integration_test.yaml
  tests/integration/conftest.py
  tests/integration/pre_run_script.sh
  tests/integration/test_jenkins.py
  tox.ini
Labels: trivial, Libraries: OK

#51 feat: rotate-credentials action
  actions.yaml
  docs/how-to/rotate-credentials.md
  docs/index.md
  src-docs/actions.py.md
  src-docs/charm.py.md
  src-docs/jenkins.py.md
  src/actions.py
  src/charm.py
  src/jenkins.py
  tests/integration/conftest.py
  tests/integration/test_jenkins.py
  tests/unit/conftest.py
  tests/unit/test_actions.py
  tests/unit/test_agent.py
  tests/unit/test_charm.py
  tests/unit/test_jenkins.py
  tests/unit/test_timerange.py
Labels: complex, Libraries: OK

#69 Changed hard-coded value to constant
  tests/integration/test_jenkins.py
Labels: trivial, Libraries: OK
