Repository canonical/jenkins-k8s-operator, pull requests merged in 2023-09, with the labels that each got.

#29 fix: eject JCasC plugin
  jenkins_rock/rockcraft.yaml
  src-docs/jenkins.py.md
  src/charm.py
  src/jenkins.py
  templates/jenkins-config.xml
  templates/jenkins.yaml
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_jenkins.py
Labels: trivial

#27 test: Git plugin integration test
  .github/workflows/integration_test.yaml
  jenkins_rock/rockcraft.yaml
  src-docs/jenkins.py.md
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/constants.py
  tests/integration/helpers.py
  tests/integration/test_agent.py
  tests/integration/test_jenkins.py
  tests/integration/test_k8s_agent.py
  tests/integration/test_machine_agent.py
  tests/integration/test_plugins.py
  tests/integration/types_.py
Labels: complex

#30 fix: >1 app per relation
  metadata.yaml
  src-docs/jenkins.py.md
  src-docs/state.py.md
  src/state.py
  tests/integration/conftest.py
  tests/integration/test_k8s_agent.py
Labels: trivial

#28 fix: typo in PR template
  .github/pull_request_template.md
Labels: trivial

#33 fix: use function level client fixture
  tests/integration/conftest.py
Labels: trivial

#32 chore: add licenserc
  .licenserc.yaml
Labels: trivial

#31 feat: COS integration
  .github/workflows/integration_test.yaml
  .gitignore
  docs/reference/integrations.md
  lib/charms/grafana_k8s/v0/grafana_dashboard.py
  lib/charms/loki_k8s/v0/loki_push_api.py
  lib/charms/observability_libs/v0/juju_topology.py
  lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  metadata.yaml
  requirements.txt
  src-docs/charm.py.md
  src-docs/cos.py.md
  src-docs/jenkins.py.md
  src/charm.py
  src/cos.py
  src/grafana_dashboards/jenkins.json
  src/jenkins.py
  src/loki_alert_rules/.gitkeep
  templates/logging.properties
  tests/integration/conftest.py
  tests/integration/helpers.py
  tests/integration/test_cos.py
  tox.ini
Labels: complex, Libraries: OK

#34 Adapt trivyignore to match existing vulnerabilities
  .trivyignore
Labels: trivial, Libraries: OK

#36 chore: trivy ignores (CI)
  .trivyignore
Labels: trivial, Libraries: OK

#35 test: LDAP plugin
  tests/integration/conftest.py
  tests/integration/constants.py
  tests/integration/helpers.py
  tests/integration/test_plugins.py
  tests/integration/types_.py
Labels: trivial, Libraries: OK

#37 fix: dashboard datasource
  src/grafana_dashboards/jenkins.json
Labels: trivial, Libraries: OK

#38 test: matrix-combinations plugin integration test
  tests/integration/files/matrix_combinations_plugin_job_xml.j2
  tests/integration/requirements.txt
  tests/integration/test_plugins.py
  tox.ini
Labels: trivial, Libraries: OK

#39 Use edge runner for unit tests
  .github/workflows/test.yaml
Labels: trivial, Libraries: OK
