Repository canonical/jenkins-k8s-operator, pull requests merged in 2024-03, with the labels that each got.

#115 ISD-1622 Jenkins agent discovery with ingress
  .trivyignore
  config.yaml
  docs/how-to/integrate-with-external-agents.md
  metadata.yaml
  src-docs/agent.py.md
  src-docs/charm.py.md
  src-docs/ingress.py.md
  src-docs/jenkins.py.md
  src-docs/state.py.md
  src/agent.py
  src/charm.py
  src/ingress.py
  src/jenkins.py
  src/state.py
  tests/integration/conftest.py
  tests/integration/test_ingress.py
  tests/unit/test_agent.py
  tests/unit/test_jenkins.py
  tests/unit/test_state.py
Labels: complex, Libraries: Out of sync

#117 Fix jenkins agent discovery
  src-docs/agent.py.md
  src-docs/charm.py.md
  src-docs/ingress.py.md
  src/agent.py
  tests/unit/test_agent.py
Labels: trivial, Libraries: Out of sync

#118 Pin requirements
  requirements.txt
Labels: trivial, Libraries: Out of sync

#119 Refactor jenkins.py
  .github/workflows/integration_test.yaml
  src-docs/jenkins.py.md
  src/actions.py
  src/agent.py
  src/charm.py
  src/jenkins.py
  tests/integration/conftest.py
  tests/unit/conftest.py
  tests/unit/test_actions.py
  tests/unit/test_charm.py
  tests/unit/test_jenkins.py
  tests/unit/test_timerange.py
Labels: trivial, Libraries: Out of sync

#120 Fix traefik path routing
  src-docs/actions.py.md
  src-docs/agent.py.md
  src-docs/charm.py.md
  src-docs/ingress.py.md
  src-docs/jenkins.py.md
  src-docs/state.py.md
  src/actions.py
  src/agent.py
  src/charm.py
  src/ingress.py
  src/jenkins.py
  src/state.py
  tests/integration/conftest.py
  tests/integration/test_ingress.py
  tests/unit/conftest.py
  tests/unit/test_actions.py
  tests/unit/test_agent.py
  tests/unit/test_charm.py
  tests/unit/test_ingress.py
  tests/unit/test_jenkins.py
  tox.ini
Labels: complex, Libraries: Out of sync

#123 Do not strip ingress prefix
  .github/workflows/integration_test.yaml
  src-docs/actions.py.md
  src-docs/agent.py.md
  src-docs/ingress.py.md
  src/actions.py
  src/agent.py
  src/ingress.py
  tests/integration/conftest.py
  tests/integration/test_ingress.py
  tests/unit/test_jenkins.py
Labels: trivial, Libraries: Out of sync

#121 ISD-1657 add declarative pipeline plugin integration test
  config.yaml
  tests/integration/helpers.py
  tests/integration/test_plugins.py
Labels: trivial, Libraries: Out of sync

#125 ISD-1656 Add resize storage documentation
  docs/how-to/resize-jenkins-storage.md
Labels: trivial, Libraries: Out of sync

#128 Create bug_report.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/enhancement_proposal.yml
Labels: Libraries: Out of sync

#113 Add version upgrade test
  .github/workflows/integration_test.yaml
  .trivyignore
  src/charm.py
  tests/integration/conftest.py
  tests/integration/constants.py
  tests/integration/helpers.py
  tests/integration/test_upgrade.py
  tests/unit/test_charm.py
Labels: trivial, Libraries: Out of sync

#109 Support for auth_proxy integration
  .github/workflows/integration_test.yaml
  .licenserc.yaml
  .trivyignore
  docs/how-to/integrate-with-iam.md
  lib/charms/oathkeeper/v0/auth_proxy.py
  metadata.yaml
  src-docs/auth_proxy.py.md
  src-docs/charm.py.md
  src-docs/jenkins.py.md
  src/agent.py
  src/auth_proxy.py
  src/charm.py
  src/jenkins.py
  src/pebble.py
  src/state.py
  templates/jenkins-auth-proxy-config.xml
  tests/integration/conftest.py
  tests/integration/dex.py
  tests/integration/files/dex.yaml
  tests/integration/requirements.txt
  tests/integration/test_auth_proxy.py
  tests/integration/test_ingress.py
  tests/unit/test_auth_proxy.py
  tests/unit/test_charm.py
  tests/unit/test_jenkins.py
  tests/unit/test_pebble.py
  tests/unit/test_state.py
  tox.ini
Labels: complex, Libraries: Out of sync

#126 Update jenkins lts version to 2.440.1
  .trivyignore
  jenkins_rock/rockcraft.yaml
  src-docs/auth_proxy.py.md
  src-docs/charm.py.md
  src-docs/pebble.py.md
  src-docs/state.py.md
  tests/integration/conftest.py
  tests/integration/test_auth_proxy.py
  tests/integration/test_jenkins.py
  tests/integration/test_proxy.py
Labels: Libraries: Out of sync
