Repository canonical/jenkins-k8s-operator, pull requests merged in 2024-01, with the labels that each got.

#87 fix: storage mount defer event & set port
  src/charm.py
  tests/unit/test_charm.py
Labels: trivial, Libraries: Out of sync

#89 fix: storage mount
  jenkins_rock/rockcraft.yaml
  src-docs/jenkins.py.md
  src-docs/state.py.md
  src/actions.py
  src/agent.py
  src/charm.py
  src/jenkins.py
  src/state.py
  tests/unit/conftest.py
  tests/unit/test_charm.py
  tests/unit/test_jenkins.py
  tests/unit/test_state.py
Labels: trivial, Libraries: Out of sync

#91 add workflow for bot approval
  .github/workflows/bot_pr_approval.yaml
Labels: trivial, Libraries: Out of sync

#93 correct workflow file name
  .github/workflows/bot_pr_approval.yaml
Labels: Libraries: Out of sync

#96 test: update deprecated label
  tests/integration/conftest.py
  tests/integration/test_machine_agent.py
Labels: bug, trivial, Libraries: Out of sync

#95 Update bot_pr_approval.yaml
  .github/workflows/bot_pr_approval.yaml
Labels: trivial, Libraries: Out of sync

#97 Add Docker plugin test
  config.yaml
  tests/integration/test_plugins.py
Labels: Libraries: Out of sync

#99 Add pipeline-groovy-lib plugin test
  config.yaml
  tests/integration/test_plugins.py
Labels: trivial, Libraries: Out of sync

#98 ISD-1511 integration test for k8s plugin
  .trivyignore
  config.yaml
  tests/integration/helpers.py
  tests/integration/test_plugins.py
Labels: complex, Libraries: Out of sync

#102 feat: tox build pipeline
  tox.ini
Labels: Libraries: Out of sync

#104 Update Jenkins version
  jenkins_rock/rockcraft.yaml
Labels: trivial, Libraries: Out of sync

#103 Add OWASP dependency check test
  config.yaml
  tests/integration/test_plugins.py
Labels: trivial, Libraries: Out of sync

#106 Downgrade Jenkins to latest LTS version
  .trivyignore
  jenkins_rock/rockcraft.yaml
  tests/integration/test_k8s_agent.py
Labels: Libraries: Out of sync

#105 Add reverse proxy plugin integration test
  config.yaml
  tests/integration/test_plugins.py
Labels: trivial, Libraries: Out of sync
