Repository canonical/jenkins-k8s-operator, pull requests merged in 2024-04, with the labels that each got.

#131 Replan when ingress ready
  .github/workflows/integration_test.yaml
  .licenserc.yaml
  src/agent.py
  src/auth_proxy.py
  src/jenkins.py
  src/pebble.py
  tests/integration/conftest.py
  tests/integration/files/identity-bundle-edge-patched.yaml
  tests/integration/test_auth_proxy.py
  tests/integration/test_external_agent.py
  tests/integration/test_ingress.py
  tests/unit/test_ingress.py
  tests/unit/test_jenkins.py
Labels: complex, Libraries: Out of sync

#146 pin resource rev due to instability
  tests/integration/files/identity-bundle-edge-patched.yaml
Labels: trivial, Libraries: Out of sync

#134 ISD-1729 Add RAM percentage JVM option and documentations
  docs/how-to/configure-jenkins-memory-usage.md
  src/pebble.py
Labels: trivial, Libraries: Out of sync

#147 Jenkins lts 2.440.2
  .trivyignore
  jenkins_rock/rockcraft.yaml
Labels: trivial, Libraries: Out of sync

#148 jenkins version 2.440.3
  jenkins_rock/rockcraft.yaml
  src-docs/agent.py.md
  src-docs/auth_proxy.py.md
  src-docs/jenkins.py.md
  src-docs/pebble.py.md
  tests/integration/test_plugins.py
Labels: trivial, Libraries: Out of sync

#149 docs: update backup file docs
  docs/how-to/resize-jenkins-storage.md
  tests/integration/test_plugins.py
Labels: Libraries: Out of sync
