Repository canonical/jenkins-k8s-operator, pull requests merged in 2025-09, with the labels that each got.

#258 fix: agent relation race condition
  docs/changelog.md
  src/agent.py
  src/auth_proxy.py
  src/jenkins.py
  tests/integration/pre_run_script.sh
  tests/unit/conftest.py
  tests/unit/test_agent.py
  tests/unit/test_jenkins.py
Labels: bug, trivial

#261 chore: eject deprecated agent relation
  charmcraft.yaml
  docs/changelog.md
  docs/explanation/agent-deprecated-relation.md
  docs/index.md
  src/agent.py
  src/state.py
  tests/integration/conftest.py
  tests/unit/conftest.py
  tests/unit/test_agent.py
Labels: trivial

#270 chore: update charm to use noble base
  charmcraft.yaml
  docs/changelog.md
  docs/explanation/charm-architecture.md
  tests/integration/conftest.py
Labels: trivial

#272 fix: reconcile agents on upgrade charm
  docs/changelog.md
  src/charm.py
Labels: bug, trivial

#276 fix: issue with jenkins name omitting relations
  docs/changelog.md
  src/state.py
  tox.ini
Labels: bug, trivial

#277 Add security policy
  SECURITY.md
Labels: documentation

#266 test: swap oathkeeper with oauth2 proxy
  charmcraft.yaml
  docs/changelog.md
  lib/charms/oauth2_proxy_k8s/v0/auth_proxy.py
  lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  lib/charms/traefik_k8s/v2/ingress.py
  src/auth_proxy.py
  tests/integration/conftest.py
  tests/integration/dex.py
  tests/integration/files/coredns.yaml.j2
  tests/integration/files/dex.yaml
  tests/integration/requirements.txt
  tests/integration/test_auth_proxy.py
  tests/unit/test_auth_proxy.py
  tox.ini
Labels: trivial
